// src/components/SignerWorkspace.vue
<script setup lang="ts">
import { reactive } from 'vue';
import { convertError } from '../common';

import { useEver } from '../providers/useEver';

const { ever, selectedAccount } = useEver();

const state = reactive({
  data: '',
  output: '',
  inProgress: false,
  error: undefined
});

const submit = async () => {
  if (state.inProgress || selectedAccount.value == null) {
    return;
  }

  state.inProgress = true;
  state.error = undefined;

  try {
    const encoded = encodeURIComponent(state.data).replace(/%([\dA-F]{2})/g, (_match, p1: any) =>
      String.fromCharCode(('0x' + p1) as any)
    );

    const output = await ever.signData({
      data: window.btoa(encoded),
      publicKey: selectedAccount.value.publicKey
    });

    state.inProgress = false;
    state.output = JSON.stringify(output, undefined, 4);
  } catch (e: any) {
    state.error = convertError(e.message);
  } finally {
    state.inProgress = false;
  }
};
</script>

<template>
  <section class="section">
    <div class="container is-fluid">
      <div class="field">
        <label class="label">Enter data to sign:</label>
        <div class="control">
          <textarea class="textarea" spellcheck="false" v-model="state.data" rows="5" />
        </div>
      </div>
      <div class="field">
        <div class="control">
          <button :disabled="state.inProgress" class="button is-primary" @click="submit">Sign</button>
        </div>
      </div>
    </div>
    <br />
    <div class="container is-fluid">
      <h5 class="title is-size-5">Output:</h5>
      <pre>{{ state.error ? state.error : state.output }}</pre>
    </div>
  </section>
</template>

// src/components/SignerWorkspace/index.tsx
import React, { useState } from 'react';
import { convertError } from '../../common';

export type SignerWorkspaceProps = {
  signData: (data: string) => Promise<object>;
};

export const SignerWorkspace: React.FC<SignerWorkspaceProps> = ({ signData }) => {
  const [data, setData] = useState<string>('');
  const [error, setError] = useState<string>();
  const [output, setOutput] = useState<string>();
  const [inProgress, setInProgress] = useState(false);

  const onSubmit = async () => {
    if (inProgress) {
      return;
    }

    setInProgress(true);
    setError(undefined);
    try {
      const output = await signData(data);
      setOutput(JSON.stringify(output));
    } catch (e) {
      console.error(e);
      setError(convertError(e.message));
    } finally {
      setInProgress(false);
    }
  };

  return (
    <>
      <section className="section">
        <div className="container is-fluid">
          <div className="field">
            <label className="label">Enter data to sign:</label>
            <div className="control">
              <textarea
                className="textarea"
                spellCheck={false}
                onChange={e => setData(e.target.value)}
                value={data}
                rows={5}
              />
            </div>
          </div>
          <div className="field">
            <div className="control">
              <button disabled={inProgress} className="button is-primary" onClick={onSubmit}>
                Sign
              </button>
            </div>
          </div>
        </div>
        <br />
        <div className="container is-fluid">
          <h5 className="title is-size-5">Output:</h5>
          <pre>{error == null ? output : error}</pre>
        </div>
      </section>
    </>
  );
};
