// src/components/VisualizerWorkspace.vue
<script setup lang="ts">
import { ref } from 'vue';
import * as core from '@core';

const input = ref('');
const state = ref({ decoded: undefined, error: undefined });

const decode = (e: Event) => {
  const boc = (e.target as HTMLInputElement).value;
  try {
    state.value = {
      decoded: core.visualize(boc),
      error: undefined
    };
  } catch (e: any) {
    state.value = {
      decoded: undefined,
      error: e.toString()
    };
  }
};
</script>

<template>
  <section class="section">
    <div class="container is-fluid">
      <div class="field">
        <label class="label">Enter base64 encoded BOC:</label>
        <div class="control">
          <textarea
            :class="['textarea', { 'is-danger': state.error != null }]"
            spellcheck="false"
            v-model="input"
            rows="5"
            @input="decode"
          />
        </div>
        <p v-if="state.error != null" class="help is-danger">{{ state.error }}</p>
      </div>
    </div>
  </section>
  <section class="section">
    <div class="container is-fluid">
      <h5 class="title is-size-5">Output:</h5>
      <pre>{{ state.decoded }}</pre>
    </div>
  </section>
</template>

// src/components/VisualizerWorkspace/index.tsx
import React from 'react';
import classNames from 'classnames';

import * as core from '@core';

export type VisualizerWorkspaceState = {
  input: string;
  decoded: string | null;
  error: string | null;
};

export class VisualizerWorkspace extends React.Component<{}, VisualizerWorkspaceState> {
  constructor(props: {}) {
    super(props);

    this.state = {
      input: '',
      decoded: null,
      error: null
    };
  }

  onInput = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    const input = event.target.value;

    try {
      const decoded = core.decode(input);
      this.setState({
        input,
        decoded,
        error: null
      });
    } catch (e: any) {
      this.setState({
        input: event.target.value,
        decoded: null,
        error: e.toString()
      });
    }
  };

  render() {
    const { input, decoded, error } = this.state;

    return (
      <>
        <section className="section">
          <div className="container is-fluid">
            <div className="field">
              <label className="label">Enter base64 encoded BOC:</label>
              <div className="control">
                <textarea
                  className={classNames('textarea', { 'is-danger': error != null })}
                  spellCheck={false}
                  onChange={this.onInput}
                  value={input}
                  rows={5}
                />
              </div>
              {error != null && <p className="help is-danger">{error}</p>}
            </div>
          </div>
        </section>
        <section className="section">
          <div className="container is-fluid">
            <h5 className="title is-size-5">Output:</h5>
            <pre>{error == null ? decoded : null}</pre>
          </div>
        </section>
      </>
    );
  }
}
