// src/components/DebuggerWorkspace.vue
<script setup lang="ts">
import { computed, nextTick, ref, shallowRef, watch } from 'vue';
import { Transaction } from 'everscale-inpage-provider';

import { useDebugger } from '../providers/useDebugger';
import { zeroPad } from '../common';

import TransactionIdForm, { TransactionResponse } from './TransactionIdForm.vue';

enum Status {
  NONE,
  SEARCH,
  APPLY,
  EXECUTE
}

type State = {
  transaction: Transaction;
  steps: number[];
  gasUsed: string[];
  gasCmds: string[];
  cmds: string[];
  stacks: string[][];
};

const { debuggerModule } = useDebugger();
const transaction = shallowRef<TransactionResponse>();
const state = shallowRef<State>();
const stackIndex = ref(0);
const status = ref<Status>(Status.NONE);

const displayedStatus = computed(() => {
  switch (status.value) {
    case Status.SEARCH:
      return 'searching transaction';
    case Status.APPLY:
      return 'applying state';
    case Status.EXECUTE:
      return 'executing';
    default:
      return undefined;
  }
});

const displayedTransaction = computed(() =>
  state.value != null ? JSON.stringify(state.value.transaction, undefined, 2) : undefined
);

watch(
  [debuggerModule, transaction],
  async ([debuggerModule, transaction], _, onCleanup) => {
    state.value = undefined;
    if (debuggerModule == null || transaction == null) {
      return;
    }

    const controller = new AbortController();
    const localState = { transactionChanged: false };
    onCleanup(() => {
      status.value = Status.NONE;
      controller.abort();
      localState.transactionChanged = true;
    });

    status.value = Status.APPLY;
    const account = await fetch('https://states.everscan.io/apply', {
      body: `{"account":"${transaction.rawTransaction.account}","lt":${transaction.rawTransaction.lt}}`,
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST',
      signal: controller.signal
    })
      .then(res => res.json())
      .then(res => res.accountBoc)
      .catch(console.error);
    if (localState.transactionChanged) {
      return;
    }

    status.value = Status.EXECUTE;
    nextTick(() => {
      if (localState.transactionChanged) {
        return;
      }
      state.value = debuggerModule.execute(account, transaction.rawTransaction.data, transaction.configBoc);
      stackIndex.value = 0;
      status.value = Status.NONE;
    }).catch(console.error);
  },
  {
    immediate: true
  }
);

function onTransactionFound(tx?: TransactionResponse) {
  status.value = Status.NONE;
  transaction.value = tx;
}

function stackFirst() {
  stackIndex.value = 0;
}

function stackLast() {
  if (state.value?.stacks.length > 0) {
    stackIndex.value = state.value?.stacks.length - 1;
  }
}

function stackBackward() {
  if (stackIndex.value > 0) {
    stackIndex.value -= 1;
  }
}

function stackForward() {
  if (stackIndex.value + 1 < state.value?.stacks.length) {
    stackIndex.value += 1;
  }
}
</script>

<template>
  <div v-if="debuggerModule != null" class="section debugger-workspace">
    <div class="container is-fluid">
      <div class="columns">
        <div class="column is-3 is-full">
          <TransactionIdForm @change="onTransactionFound" @search="status = Status.SEARCH" />
          <template v-if="displayedStatus != null">Status: {{ displayedStatus }}</template>
          <pre v-if="displayedTransaction != null">{{ displayedTransaction }}</pre>
        </div>
        <div v-if="state != null" class="column is-3 is-flex-direction-row noselect">
          <h3 class="is-size-4 is-flex is-flex-direction-row">
            Commands
            <button class="button is-light ml-auto mr-2" @click="stackFirst()">
              <span class="icon"><i class="fas fa-fast-backward" /></span>
            </button>
            <button class="button is-info mr-2" :disabled="stackIndex === 0" @click="stackBackward()">
              <span class="icon"><i class="fas fa-backward" /></span>
            </button>
            <button
              class="button is-info mr-2"
              :disabled="stackIndex + 1 >= state.stacks.length"
              @click="stackForward()"
            >
              <span class="icon"><i class="fas fa-forward"></i></span>
            </button>
            <button class="button is-light" @click="stackLast()">
              <span class="icon"><i class="fas fa-fast-forward" /></span>
            </button>
          </h3>
          <hr />
          <div class="command-list-container">
            <ul class="command-list is-family-monospace">
              <li v-for="(step, i) in state.steps" :key="i">
                <span class="list-index">{{ zeroPad(step, 4) }}</span>
                <span :class="['tag', i === stackIndex ? 'is-success' : 'is-light']" @click="stackIndex = i">{{
                  state.cmds[i]
                }}</span>
              </li>
            </ul>
          </div>
        </div>
        <div v-if="state != null" class="column is-6 noselect">
          <h2 class="is-size-4 is-flex is-flex-direction-row">
            <button class="button is-light mr-2" v-clipboard="state.cmds[stackIndex]">
              <span class="icon"><i class="fas fa-copy" /></span>
            </button>
            <span class="command-title">{{ state.cmds[stackIndex] }}</span>
          </h2>
          <hr />
          <div class="command-list-container">
            <ul class="command-list is-family-monospace">
              <li v-for="(item, i) in state.stacks[stackIndex]" :key="i" class="is-flex">
                <span class="list-index">{{ i }}</span>
                <span class="tag is-light is-full">{{ item }}</span>
                <button class="button is-small is-light ml-2 mr-2" v-clipboard="item">
                  <span class="icon"><i class="fas fa-copy" /></span>
                </button>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div v-else class="hero is-fullheight-with-navbar">
    <div class="hero-body is-justify-content-center">
      <div>
        <p class="title">Loading debugger...</p>
      </div>
    </div>
  </div>
</template>

<style lang="scss">
.debugger-workspace {
  max-height: 100%;

  .command-list-container {
    overflow-y: scroll;
    max-height: calc((1.5em + 0.2em) * 40 + 0.75em);
  }

  .command-title {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
  }

  .command-list {
    width: 100%;

    li {
      cursor: pointer;
      display: flex;
      flex-direction: row;
      justify-content: start;
      margin-bottom: 0.2em;
      height: 1.5em;

      .list-index {
        width: 4em;
      }

      .tag {
        width: 100%;
        display: inline;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        line-height: 2em;
      }

      button {
        height: 2em;
      }
    }
  }
}
</style>

// src/components/DebuggerWorkspace/index.tsx
import React, { useEffect, useState } from 'react';
import { CopyToClipboard } from 'react-copy-to-clipboard';
import * as core from '@core';

import './style.scss';
import classNames from 'classnames';

export type DebuggerWorkspaceProps = {};

type TransactionIdFormProps = {
  inProgress: boolean;
  currentId?: string;
  onChangeId: (id: string) => void;
};

const txRegex = /^[\da-fA-F]{64}$/;

const TransactionIdForm: React.FC<TransactionIdFormProps> = ({ inProgress, currentId, onChangeId }) => {
  const [id, setId] = useState<string>('');

  const isSame = id.trim().toLowerCase() === currentId?.trim().toLowerCase();
  const isValid = txRegex.test(id);

  return (
    <>
      <div className="field has-addons">
        <div className="control is-expanded">
          <input
            className="input"
            type="text"
            value={id}
            spellCheck={false}
            disabled={inProgress}
            onChange={event => {
              setId(event.target.value.trim());
            }}
          />
          <p className="help">Transaction id</p>
        </div>
        <div className="control">
          <button
            className="button is-info"
            disabled={inProgress || isSame || !isValid}
            onClick={() => {
              !inProgress && !isSame && isValid && onChangeId(id);
            }}
          >
            Search
          </button>
        </div>
      </div>
    </>
  );
};

const STATES_URL = 'https://states.everscan.io/apply';

const getState = (address: string, lt: string): Promise<string> =>
  fetch(STATES_URL, {
    body: `{"account":"${address}","lt":${lt}}`,
    headers: {
      'Content-Type': 'application/json'
    },
    method: 'POST'
  }).then(res => res.json());

const GQL_URL = 'https://gra01.main.everos.dev/graphql';

const findTransactionById = (id: string): Promise<Transaction | undefined> =>
  fetch(GQL_URL, {
    body: JSON.stringify({
      operationName: null,
      variables: {},
      query: `{transactions(filter:{id:{eq:"${id}"}}){lt(format:DEC),now,account_addr,in_message{boc}}}`
    }),
    headers: {
      'Content-Type': 'application/json'
    },
    method: 'POST'
  })
    .then(res => res.json())
    .then(res => {
      if (typeof res !== 'object' || res == null) {
        return;
      }
      const data = res['data'];
      if (typeof data !== 'object' || data == null) {
        return;
      }

      const transactions = data['transactions'];
      if (!Array.isArray(transactions) || transactions.length == 0) {
        return;
      }
      const item = transactions[0];
      if (typeof item !== 'object' || item == null) {
        return;
      }
      const lt = item['lt'];
      if (typeof lt !== 'string') {
        return;
      }
      const now = item['now'];
      if (typeof now !== 'number') {
        return;
      }
      const accountAddr = item['account_addr'];
      if (typeof accountAddr !== 'string') {
        return;
      }
      const inMessage = item['in_message'];
      if (typeof inMessage !== 'object' || inMessage == null) {
        return;
      }
      const messageBoc = inMessage['boc'];
      if (typeof messageBoc !== 'string') {
        return;
      }
      return {
        lt,
        now,
        accountAddr,
        messageBoc
      };
    });

type Transaction = {
  lt: string;
  now: number;
  accountAddr: string;
  messageBoc: string;
};

enum Status {
  NONE,
  SEARCH_TRANSACTION,
  APPLY_STATE,
  EXECUTE
}

const zeroPad = (num: number, places: number) => {
  const zero = places - num.toString().length + 1;
  return Array(+(zero > 0 && zero)).join('0') + num;
};

export const DebuggerWorkspace: React.FC<DebuggerWorkspaceProps> = ({}) => {
  const [inProgress, setInProgress] = useState(false);
  const [transaction, setTransaction] = useState<Transaction>();
  const [status, setStatus] = useState(Status.NONE);
  const [stackIndex, setStackIndex] = useState<number>();
  const [data, setData] = useState<any>();
  const [txId, setTxId] = useState<string>();

  useEffect(() => {
    if (txId == null) {
      return;
    }

    setInProgress(true);
    setStatus(Status.SEARCH_TRANSACTION);
    findTransactionById(txId)
      .then(async transaction => {
        setTransaction(transaction);
        if (transaction != null) {
          setStatus(Status.APPLY_STATE);
          const state = await getState(transaction.accountAddr, transaction.lt);
          setStatus(Status.EXECUTE);
          setStackIndex(undefined);

          const data = core.execute(state, transaction.messageBoc, transaction.now, transaction.lt);
          setData(data);
          if (data.stacks.length > 0) {
            setStackIndex(0);
          }
        }
      })
      .catch(console.error)
      .finally(() => {
        setStatus(Status.NONE);
        setInProgress(false);
      });
  }, [txId]);

  useEffect(() => {
    if (transaction == null) {
      setData(undefined);
    } else {
      // setTransaction(core.execute);
    }
  }, [transaction]);

  return (
    <section className="section debugger-workspace">
      <div className="container is-fluid">
        <div className="columns">
          <div className="column is-3 is-full">
            <TransactionIdForm inProgress={inProgress} currentId={txId} onChangeId={setTxId} />
            {status != Status.NONE && (
              <>
                Status:{' '}
                {status == Status.SEARCH_TRANSACTION
                  ? 'search transaction'
                  : status == Status.APPLY_STATE
                  ? 'apply state'
                  : 'execute'}
              </>
            )}
            {data != null && <pre>{JSON.stringify((data as any).transaction, undefined, 4)}</pre>}
          </div>
          <div className="column is-3 is-flex-direction-row noselect">
            {data != null && (
              <>
                <h3 className="is-size-4 is-flex is-flex-direction-row">
                  Commands{' '}
                  <button className="button is-light ml-auto mr-2" onClick={() => setStackIndex(0)}>
                    <span className="icon">
                      <i className="fas fa-fast-backward"></i>
                    </span>
                  </button>
                  <button
                    className="button is-info mr-2"
                    disabled={stackIndex == null || stackIndex == 0}
                    onClick={() => {
                      if (stackIndex != null && stackIndex > 0) {
                        setStackIndex(stackIndex - 1);
                      }
                    }}
                  >
                    <span className="icon">
                      <i className="fas fa-backward"></i>
                    </span>
                  </button>
                  <button
                    className="button is-info mr-2"
                    disabled={stackIndex == null || stackIndex + 1 >= data.stacks.length}
                    onClick={() => {
                      if (stackIndex != null && stackIndex + 1 < data.stacks.length) {
                        const index = stackIndex + 1;
                        setStackIndex(index);
                      }
                    }}
                  >
                    <span className="icon">
                      <i className="fas fa-forward"></i>
                    </span>
                  </button>
                  <button
                    className="button is-light"
                    onClick={() => {
                      if (data.stacks.length > 0) {
                        const index = data.stacks.length - 1;
                        setStackIndex(index);
                      }
                    }}
                  >
                    <span className="icon">
                      <i className="fas fa-fast-forward"></i>
                    </span>
                  </button>
                </h3>
                <hr></hr>
                <div className="command-list-container">
                  <ul className="command-list is-family-monospace">
                    {data.steps.map((step: number, i: number) => {
                      return (
                        <li key={i}>
                          <span className="list-index">{zeroPad(step, 4)}</span>
                          <span
                            className={classNames('tag', {
                              'is-light': i != stackIndex,
                              'is-success': i == stackIndex
                            })}
                            onClick={() => {
                              setStackIndex(i);
                            }}
                          >
                            {data.cmds[i]}
                          </span>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              </>
            )}
          </div>
          <div className="column is-6 noselect">
            {data != null && stackIndex != null && (
              <>
                <h2 className="is-size-4 is-flex is-flex-direction-row">
                  <CopyToClipboard text={data.cmds[stackIndex]}>
                    <button className="button is-light mr-2">
                      <span className="icon">
                        <i className="fas fa-copy"></i>
                      </span>
                    </button>
                  </CopyToClipboard>
                  <span className="command-title">{data.cmds[stackIndex]}</span>
                </h2>
                <hr></hr>
                <div className="command-list-container">
                  <ul className="command-list is-family-monospace">
                    {data.stacks[stackIndex].map((item: string, i: number) => {
                      return (
                        <li key={i} className="is-flex">
                          <span className="list-index">{i}</span>
                          <span className="tag is-light is-full">{item}</span>
                          <CopyToClipboard text={data.stacks[stackIndex]}>
                            <button className="button is-small is-light ml-2 mr-2">
                              <span className="icon">
                                <i className="fas fa-copy"></i>
                              </span>
                            </button>
                          </CopyToClipboard>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};
