// src/components/EntityBuilderItem/index.tsx
import React from 'react';
import classNames from 'classnames';

import * as core from '@core';

import './style.scss';

type AbiValueData<K extends core.AbiValue['type']> = Extract<core.AbiValue, { type: K }>['data'];

type HandlerArgs<K extends core.AbiValue['type']> = {
  abi: core.AbiParamType;
  value: AbiValueData<K>;
  onChange: (newData: AbiValueData<K>) => void;
};

type Handler<T extends core.AbiValue['type'] = core.AbiValue['type']> = (args: HandlerArgs<T>) => React.ReactNode;

const makeTextField: Handler = ({ value, onChange }): React.ReactNode => (
  <div className="control">
    <input
      className="input is-small"
      spellCheck={false}
      type="text"
      value={value as any}
      onChange={e => {
        onChange(e.target.value as any);
      }}
    />
  </div>
);

const makeTextAreaField: Handler = ({ value, onChange }): React.ReactNode => (
  <div className="control">
    <textarea
      className="textarea is-small"
      spellCheck={false}
      value={value as any}
      onChange={e => {
        onChange(e.target.value as any);
      }}
      rows={2}
    />
  </div>
);

const makeBoolField: Handler = ({ value, onChange }): React.ReactNode => (
  <div className="control is-unselectable">
    <label className="checkbox">
      <input
        type="checkbox"
        checked={value as any}
        onChange={() => {
          onChange(!value as any);
        }}
      />
      &nbsp;
      {value?.toString() || false}
    </label>
  </div>
);

const makeTupleField: Handler = ({ abi, value, onChange }): React.ReactNode => {
  if (abi.kind !== 'tuple' || value == null) {
    return null;
  }
  return abi.info.types.map((abi, i) => {
    return (
      <EntityBuilderItem
        key={i}
        value={(value as any)[i]}
        abi={abi}
        onChange={newValue => {
          (value as any)[i] = newValue;
          onChange(value);
        }}
      />
    );
  });
};

const makeArrayField: Handler = ({ abi, value, onChange }): React.ReactNode => {
  if (abi.kind !== 'array' || value == null) {
    return null;
  }
  const values = value as core.AbiValue[];

  return (
    <>
      {values.map((itemValue, i) => (
        <EntityBuilderItem
          key={i}
          value={itemValue}
          abi={{ name: `element[${i}]`, type: abi.info.type }}
          onChange={newValue => {
            (value as any[])[i] = newValue;
            onChange(value);
          }}
          onDelete={() => {
            (value as any[]).splice(i, 1);
            onChange(value);
          }}
        />
      ))}
      <button
        className="button is-fullwidth is-small"
        onClick={() => {
          const newValue = JSON.parse(JSON.stringify((abi.info as any).defaultValue));
          (value as any[]).push(newValue);
          onChange(value);
        }}
      >
        Add element
      </button>
    </>
  );
};

const makeMapField: Handler<'map'> = ({ abi, onChange, value }) => {
  if (abi.kind !== 'map') return null;

  const defaultKey = (abi.info as any).defaultKey as core.AbiValue;
  const defaultValue = (abi.info as any).defaultValue as core.AbiValue;

  const findRecordByKey = (someKey: core.AbiValue): [[core.AbiValue, core.AbiValue] | undefined, number] => {
    const index = value.findIndex(([key]) => key === someKey);
    const tuple = value[index];
    return [tuple, index];
  };

  function onChangeKey(newKey: any, oldKey: any) {
    const [record] = findRecordByKey(oldKey);
    if (!record) return console.warn('Cant find record to change');

    record[0] = newKey;
    onChange(value);
  }
  function onChangeValue(newData: any, key: any) {
    const [record] = findRecordByKey(key);
    if (!record) return console.warn('Cant find record to change');

    record[1] = newData;
    onChange(value);
  }

  function onDelete(key: any) {
    const [, indexToDelete] = findRecordByKey(key);
    const updatedValues = value.filter((_, index) => index !== indexToDelete);
    onChange(updatedValues);
  }

  return (
    <>
      {value.map(([key, value], index) => {
        return (
          <div key={index} className="is-flex is-flex-direction-row">
            <EntityBuilderItem
              className="is-flex-grow-1 is-key"
              abi={{ name: 'map-key', type: abi.info.key }}
              value={key}
              onChange={newKey => onChangeKey(newKey, key)}
              onDelete={() => onDelete(key)}
            />
            <EntityBuilderItem
              className="mb-3 ml-1 is-value is-flex-grow-5"
              abi={{ name: 'map-value', type: abi.info.value }}
              value={value}
              onChange={newValue => onChangeValue(newValue, key)}
            />
          </div>
        );
      })}
      <button
        className="button is-fullwidth is-small"
        onClick={() => {
          const clone = JSON.parse(JSON.stringify(defaultValue));
          value.push([defaultKey, clone]);
          onChange(value);
        }}
      >
        Add entry
      </button>
    </>
  );
};

const HANDLERS: {
  [K in core.AbiValue['type']]: Handler<any>;
} = {
  uint: makeTextField,
  int: makeTextField,
  varuint: makeTextField,
  varint: makeTextField,
  bool: makeBoolField,
  tuple: makeTupleField,
  array: makeArrayField,
  cell: makeTextAreaField,
  address: makeTextAreaField,
  bytes: makeTextAreaField,
  string: makeTextAreaField,
  pubkey: makeTextAreaField,
  map: makeMapField
};

const getAbiTypeSignature = (param: core.AbiParamType): string => {
  if (param.kind == 'uint' || param.kind == 'int' || param.kind == 'varuint' || param.kind == 'varint') {
    return `${param.kind}${param.info.size}`;
  } else if (param.kind == 'array') {
    return `${getAbiTypeSignature(param.info.type)}[]`;
  } else if (param.kind == 'fixedarray') {
    return `${getAbiTypeSignature(param.info.type)}[${param.info.size}]`;
  } else if (param.kind == 'fixedbytes') {
    return `${param.kind}[${param.info.size}]`;
  } else if (param.kind == 'map') {
    return `${param.kind}(${getAbiTypeSignature(param.info.key)}, ${getAbiTypeSignature(param.info.value)})`;
  } else {
    return param.kind;
  }
};

type EntityBuilderItemProps = {
  abi: core.AbiParam;
  value: core.AbiValue;
  className?: string;
  onChange?: (data: core.AbiValue) => void;
  onDelete?: () => void;
};

export class EntityBuilderItem extends React.Component<EntityBuilderItemProps> {
  constructor(props: EntityBuilderItemProps) {
    super(props);
  }

  render() {
    const { abi, value, className, onChange, onDelete } = this.props;

    const type = abi.type;

    const showInput = () => {
      const handler = HANDLERS[value.type];
      if (handler == null) {
        return 'Unsupported';
      }

      return handler({
        abi: abi.type,
        value: value.data,
        onChange: (data: any) =>
          onChange?.({
            type: value.type,
            data
          } as any)
      });
    };

    const isGroup = abi.type.kind == 'tuple';

    const name = `${abi.name != '' ? `${abi.name}: ` : ''}${getAbiTypeSignature(type)}`;

    return (
      <div className={classNames('field box p-3', className)}>
        {onDelete == null ? (
          <span className={classNames('tag', { 'mb-3': isGroup })}>{name}</span>
        ) : (
          <div className="tags has-addons mb-0">
            <span className="tag mb-0">{name}</span>
            <a className="tag is-delete mb-0" onClick={onDelete} />
          </div>
        )}
        {showInput()}
      </div>
    );
  }
}

// src/components/EntityBuilderItem.vue
<script setup lang="ts">
import { computed } from 'vue';
import { TokenValue } from 'everscale-inpage-provider';

import { Structure } from '../common';

const props = defineProps<{
  structure: Structure;
  customName?: string;
  value: TokenValue<string>;
  removable?: boolean;
}>();

const emit = defineEmits<{
  (e: 'change', value: TokenValue<string>): void;
  (e: 'removed'): void;
}>();

const name = computed(() => props.customName || props.structure.name);
const title = computed(() => (name.value.length > 0 ? `${name.value}: ${props.structure.type}` : props.structure.type));

type MapEntry = [TokenValue<string>, TokenValue<string>];

function ensureMapParam(structure: Structure, value: TokenValue<string>): asserts value is MapEntry[] {
  if (structure.fieldType !== 'map') {
    throw new Error('Invalid value');
  }
}

function findEntryByKey(key: TokenValue<string>): readonly [MapEntry | undefined, number] {
  ensureMapParam(props.structure, props.value);
  const index = props.value.findIndex(([entryKey]) => entryKey == key);
  const entry = props.value[index];
  return [entry, index];
}

function onInput(event: InputEvent) {
  const value = (event.target as HTMLInputElement).value;
  emit('change', value);
}

function onChangeTupleValue(name: string, value: TokenValue<string>) {
  (props.value as { [name: string]: TokenValue<string> })[name] = value;
}

function onChangeMapKey(oldKey: TokenValue<string>, newKey: TokenValue<string>) {
  const [entry] = findEntryByKey(oldKey);
  if (entry == null) return console.warn('Old key not found');
  entry[0] = newKey;
}

function onChangeMapValue(key: TokenValue<string>, value: TokenValue<string>) {
  const [entry] = findEntryByKey(key);
  if (entry == null) return console.warn('Old key not found');
  entry[1] = value;
}

function onDeleteMapEntry(key: TokenValue<string>) {
  const [, index] = findEntryByKey(key);
  (props.value as MapEntry[]).splice(index, 1);
}

function onAddMapEntry() {
  const key = JSON.parse(JSON.stringify(props.structure.key.defaultValue));
  const value = JSON.parse(JSON.stringify(props.structure.value.defaultValue));
  (props.value as MapEntry[]).push([key, value]);
}

function onChangeArrayElement(i: number, value: TokenValue<string>) {
  (props.value as TokenValue<string>[])[i] = value;
}

function onAddArrayElement() {
  const value = JSON.parse(JSON.stringify(props.structure.value.defaultValue));
  (props.value as TokenValue<string>[]).push(value);
}

function onDeleteArrayElement(i: number) {
  (props.value as TokenValue<string>[]).splice(i, 1);
}

function onOptionalChange() {
  emit('change', props.value == null ? props.structure.defaultValue : null);
}
</script>

<template>
  <div class="field box p-3">
    <div v-if="structure.optional === true" class="tags has-addons mb-0">
      <span class="tag mb-0">{{ title }}</span>
      <label class="tag mb-0 checkbox">
        <input type="checkbox" :checked="value != null" @change="onOptionalChange" />
      </label>
    </div>
    <div v-else-if="removable" class="tags has-addons mb-0">
      <span class="tag mb-0">{{ title }}</span>
      <a class="tag is-delete mb-0" @click="emit('removed')" />
    </div>
    <span v-else :class="['tag', { 'mb-3': structure.fieldType === 'tuple' }]">{{ title }}</span>

    <template v-if="value != null">
      <div v-if="structure.fieldType === 'checkbox'" class="control is-unselectable">
        <label class="checkbox">
          <input type="checkbox" :checked="value" @change="emit('change', !value)" />
        </label>
      </div>
      <div v-else-if="structure.fieldType === 'number'">
        <div class="control">
          <input class="input is-small" spellcheck="false" type="text" :value="value" @input="onInput" />
        </div>
      </div>
      <div v-else-if="structure.fieldType === 'text'">
        <div class="control">
          <textarea class="textarea is-small" rows="2" spellcheck="false" :value="value" @input="onInput" />
        </div>
      </div>
      <template v-else-if="structure.fieldType === 'tuple'">
        <EntityBuilderItem
          v-for="(item, i) in structure.components"
          :key="i"
          :structure="item"
          :value="value[item.name]"
          @change="onChangeTupleValue(item.name, $event)"
        />
      </template>
      <template v-else-if="structure.fieldType === 'array'">
        <EntityBuilderItem
          v-for="(item, i) in value"
          :key="i"
          :structure="structure.value"
          removable
          :custom-name="`${name}[${i}]`"
          :value="item"
          @change="onChangeArrayElement(i, $event)"
          @removed="onDeleteArrayElement(i)"
        />
        <button class="button is-fullwidth is-small" @click="onAddArrayElement()">Add element</button>
      </template>
      <template v-else-if="structure.fieldType === 'map'">
        <div v-for="(item, i) in value" :key="i" class="is-flex is-flex-direction-row">
          <EntityBuilderItem
            class="is-flex-grow-1 is-key"
            :structure="structure.key"
            removable
            custom-name="Entry key"
            :value="item[0]"
            @change="onChangeMapKey(item[0], $event)"
            @removed="onDeleteMapEntry(item[0])"
          />
          <EntityBuilderItem
            class="is-flex-grow-5 is-value mb-3 ml-1"
            :structure="structure.value"
            custom-name="Entry value"
            :value="item[1]"
            @change="onChangeMapValue(item[0], $event)"
          />
        </div>
        <button class="button is-fullwidth is-small" @click="onAddMapEntry()">Add entry</button>
      </template>
    </template>
  </div>
</template>

<style lang="scss">
@import '../styles/constants';

.wide {
  width: 100%;
}

.field {
  &.is-key {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }

  &.is-value {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }
}
</style>
