// src/components/Navbar/index.tsx
import React from 'react';
import classNames from 'classnames';
import { Link, useLocation } from 'react-router-dom';
import { Address } from 'everscale-inpage-provider';
import { convertAddress, convertTons } from '../../common';
import { CopyToClipboard } from 'react-copy-to-clipboard';

type NavbarItemProps = {
  path: string;
};

const NavbarItem: React.FC<NavbarItemProps> = ({ path, children }) => {
  const { pathname } = useLocation();
  const isActive = path == pathname;

  return (
    <Link
      className={classNames({
        'navbar-item': true,
        'is-active': isActive,
        'is-primary': isActive
      })}
      to={path}
    >
      {children}
    </Link>
  );
};

export type NavbarProps = {
  hasTonProvider: boolean;
  walletAddress?: Address;
  walletBalance?: string;
  isConnecting: boolean;
  onConnect: () => void;
  onChangeAccount: () => void;
  onDisconnect: () => void;
};

export const Navbar: React.FC<NavbarProps> = ({
  hasTonProvider,
  walletAddress,
  walletBalance,
  isConnecting,
  onConnect,
  onChangeAccount,
  onDisconnect
}) => {
  return (
    <nav className="navbar is-spaced" role="navigation" aria-label="main navigation">
      <div className="navbar-brand">
        <Link className="navbar-item" to="/">
          💎
        </Link>
      </div>

      <div id="navbarBasicExample" className="navbar-menu">
        <div className="navbar-start">
          <NavbarItem path="/executor">Executor</NavbarItem>
          <NavbarItem path="/visualizer">Visualizer</NavbarItem>
          <NavbarItem path="/serializer">Serializer</NavbarItem>
          <NavbarItem path="/signer">Signer</NavbarItem>
          <NavbarItem path="/debugger">Debugger</NavbarItem>
        </div>
        <div className="navbar-end">
          <div className="navbar-item">
            <div className="buttons">
              {hasTonProvider ? (
                walletAddress == null ? (
                  <button
                    className={classNames('button', 'is-primary', { 'is-loading': isConnecting })}
                    onClick={onConnect}
                  >
                    <strong>Connect wallet</strong>
                  </button>
                ) : (
                  <>
                    {walletBalance != null && (
                      <CopyToClipboard text={walletBalance}>
                        <button className="button is-white">{convertTons(walletBalance)} EVER</button>
                      </CopyToClipboard>
                    )}
                    <div className="field has-addons">
                      <div className="control">
                        <CopyToClipboard text={walletAddress.toString()}>
                          <button className="button is-light">{convertAddress(walletAddress.toString())}</button>
                        </CopyToClipboard>
                      </div>
                      <div className="control">
                        <button
                          className={classNames('button', { 'is-loading': isConnecting })}
                          onClick={onChangeAccount}
                        >
                          <span className="icon">
                            <i className="fas fa-sync-alt" />
                          </span>
                        </button>
                      </div>
                      <div className="control">
                        <button className={classNames('button', { 'is-loading': isConnecting })} onClick={onDisconnect}>
                          <span className="icon">
                            <i className="fas fa-sign-out-alt" />
                          </span>
                        </button>
                      </div>
                    </div>
                  </>
                )
              ) : (
                <a
                  className="button is-light"
                  target="_blank"
                  href="https://chrome.google.com/webstore/detail/ton-crystal-wallet/cgeeodpfagjceefieflmdfphplkenlfk"
                >
                  <strong>Install wallet</strong>
                  <span className="icon">
                    <i className="fa fa-external-link-alt" />
                  </span>
                </a>
              )}
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};

// src/components/Navbar.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { convertAddress, convertTons } from '../common';

import { useEver } from '../providers/useEver';

import NavbarItem from './NavbarItem.vue';

const { hasProvider, selectedAccount, selectedAccountBalance, connectToWallet, changeAccount, disconnect } = useEver();

const isConnecting = ref(false);
const doConnectToWallet = async () => {
  isConnecting.value = true;
  connectToWallet().finally(() => (isConnecting.value = false));
};

const doChangeAccount = async () => {
  isConnecting.value = true;
  changeAccount().finally(() => (isConnecting.value = false));
};

const address = computed(() => convertAddress(selectedAccount.value?.address.toString()));
const balance = computed(() => convertTons(selectedAccountBalance.value));
</script>

<template>
  <nav class="navbar is-spaced" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <router-link class="navbar-item" to="/"> 💎</router-link>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <NavbarItem path="/executor">Executor</NavbarItem>
        <NavbarItem path="/visualizer">Visualizer</NavbarItem>
        <NavbarItem path="/serializer">Serializer</NavbarItem>
        <NavbarItem path="/signer">Signer</NavbarItem>
        <NavbarItem path="/debugger">Debugger</NavbarItem>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <template v-if="hasProvider">
              <button
                v-if="selectedAccount == null"
                :class="['button is-primary', { 'is-loading': isConnecting }]"
                @click="doConnectToWallet"
              >
                <strong>Connect wallet</strong>
              </button>
              <template v-else>
                <button
                  v-if="selectedAccountBalance != null"
                  class="button is-white"
                  v-clipboard="selectedAccountBalance"
                >
                  {{ balance }} EVER
                </button>
                <div class="field has-addons">
                  <div class="control">
                    <button class="button is-light" v-clipboard="selectedAccount.address.toString()">
                      {{ address }}
                    </button>
                  </div>
                  <div class="control">
                    <button :class="['button', { 'is-loading': isConnecting }]" @click="doChangeAccount">
                      <span class="icon"><i class="fas fa-sync-alt" /></span>
                    </button>
                  </div>
                  <div class="control">
                    <button :class="['button', { 'is-loading': isConnecting }]" @click="disconnect">
                      <span class="icon"><i class="fas fa-sign-out-alt" /></span>
                    </button>
                  </div>
                </div>
              </template>
            </template>
            <template v-else>
              <a
                class="button is-light"
                target="_blank"
                href="https://chrome.google.com/webstore/detail/ever-wallet/cgeeodpfagjceefieflmdfphplkenlfk"
              >
                <strong>Install wallet</strong>
                <span class="icon"><i class="fa fa-external-link-alt" /></span>
              </a>
            </template>
          </div>
        </div>
      </div>
    </div>
  </nav>
</template>
